### ISSUE TITLE
Add custom color

### ISSUE THREAD

**Issue by schriftgestalt** [jenskutilek/Glyphs-Scripts#1]
https://github.com/jenskutilek/Glyphs-Scripts/blob/1db9af1bbd2769627ddbd92a765e597279ae6d97/Layers/Apply%20UFO%20Layer%20Colors.py#L40

When you can’t map the color, you could use a custom color:
```
    layer.colorObject = NSColor.colorWithDeviceRed_green_blue_alpha_(r, g, b, a)
```

**Comment by jenskutilek** [comment]
Thanks! I saw the layer.colorObject, but thought it was for something else, like the layer color of color fonts.
