### ISSUE TITLE
Curve EQ is causing strange distortions for me, in slanted/italic fonts

### ISSUE THREAD

**Issue by arrowtype** [jenskutilek/Glyphs-Scripts#3]
The current version of Curve EQ is causing curves to distort in a very strange way, though only in italic/slanted fonts (and consistently in these).

https://user-images.githubusercontent.com/45946693/144729098-513e968b-3262-4f60-b8f8-2b23feeae685.mp4

By comparison, here it is, working as expected in an upright font, in a glyph with the same (or very similar) point structure:

https://user-images.githubusercontent.com/45946693/144729223-2d5c26db-9e24-412b-b0f0-3b939281cd6c.mp4

It does seem to be working as expected in RoboFont, so this might be something in the way Glyphs handles slanted coordinates differently than RF.

https://user-images.githubusercontent.com/45946693/144729354-01ab34a3-773c-49be-b93f-3a8eb2d6b2d5.mp4

Let me know if I can provide any more useful information here. Thanks for porting this over, and sorry there have been a few bumps!

---

Glyphs 3.0.4 (3105)

macOS Catalina

RoboFont 4.1b

**Comment by jenskutilek** [comment]
That's really "interesting" ;) I suspect that it may have to do with the start point placement? Glyphs allows start points of a contour to be off-curve points. Maybe that's the reason. I'll have a look as soon as I find the time.

**Comment by arrowtype** [comment]
Hmm, yeah, I could see it being an issue of Glyphs messing with the contour start points! I am opening UFOs in Glyphs, after all, so I suppose this is a bit of an edge case.

**Comment by jenskutilek** [comment]
Fixed in [75040f2d2d7e993744a5f17afe217faf6a32f25b](https://github.com/jenskutilek/Curve-Equalizer/commit/2ddaf7c5a31f6acabc7509cfeb370f51074fd488) for the plugin and c9885a2eefc0abf1033f4a981734ca42d1e3ef80 for the "balance" script.
